# Generated by Django 5.0.6 on 2025-08-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMB_App', '0002_message_created_message_modified_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMB_App.user'),
            preserve_default=False,
        ),
    ]
